# Generated by Django 5.1.6 on 2025-02-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='NIE',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
